# Generated by Django 5.0.3 on 2024-04-04 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="Nachname"),
                ),
                (
                    "first_name",
                    models.CharField(max_length=255, verbose_name="Vorname"),
                ),
            ],
            options={
                "verbose_name": "Arbeitnehmer/in",
                "verbose_name_plural": "Arbeitnehmer/innen",
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Restaurant",
                "verbose_name_plural": "Restaurants",
            },
        ),
        migrations.CreateModel(
            name="Volume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Bezeichnung")),
            ],
            options={
                "verbose_name": "Aktenband",
                "verbose_name_plural": "Aktenbände",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("begin", models.TimeField(verbose_name="Beginn der Arbeitszeit")),
                ("end", models.TimeField(verbose_name="Ende der Arbeitszeit")),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hoursinrestaurant.restaurant",
                        verbose_name="Restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mitarbeiter",
                "verbose_name_plural": "Mitarbeiter",
            },
        ),
        migrations.CreateModel(
            name="Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page", models.CharField(max_length=255, verbose_name="Seite")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hoursinrestaurant.employee",
                        verbose_name="Arbeitnehmer/in",
                    ),
                ),
                (
                    "volume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hoursinrestaurant.volume",
                        verbose_name="Aktenband",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stundenzettel",
                "verbose_name_plural": "Stundenzettel",
            },
        ),
        migrations.CreateModel(
            name="WorkingDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                ("begin", models.TimeField(verbose_name="Beginn der Arbeitszeit")),
                ("end", models.TimeField(verbose_name="Ende der Arbeitszeit")),
                (
                    "break_time",
                    models.PositiveIntegerField(verbose_name="Pause (in Minuten)"),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="working_days",
                        to="hoursinrestaurant.sheet",
                        verbose_name="Stundenzettel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arbeitstag",
                "verbose_name_plural": "Arbeitstage",
            },
        ),
    ]
