# Generated by Django 5.0.3 on 2024-09-17 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoursinrestaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sheet",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sheets",
                to="hoursinrestaurant.employee",
                verbose_name="Arbeitnehmer/in",
            ),
        ),
        migrations.DeleteModel(
            name="Staff",
        ),
    ]
