# Generated by Django 5.0.3 on 2024-09-17 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoursinrestaurant", "0002_alter_sheet_employee_delete_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.CharField(
                        choices=[
                            ("1", "Montag"),
                            ("2", "Dienstag"),
                            ("3", "Mittwoch"),
                            ("4", "Donnerstag"),
                            ("5", "Freitag"),
                            ("6", "Sonnabend"),
                            ("7", "Sonntag"),
                        ],
                        max_length=1,
                        verbose_name="Wochentag",
                    ),
                ),
                ("begin", models.DateField(verbose_name="Gültig von")),
                ("end", models.DateField(verbose_name="Gültig bis")),
                (
                    "opening",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Öffnungszeiten"
                    ),
                ),
                ("hours", models.FloatField(verbose_name="Personenstunden")),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staffs",
                        to="hoursinrestaurant.restaurant",
                        verbose_name="Restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mitarbeiterbedarf",
                "verbose_name_plural": "Mitarbeiterbedarf",
            },
        ),
    ]
