# Generated by Django 5.0.3 on 2024-09-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoursinrestaurant", "0003_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="Remarks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Leerzeilen erzeugen Absätze", verbose_name="Text"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vorbemerkung",
                "verbose_name_plural": "Vorbemerkungen",
            },
        ),
    ]
