# Generated by Django 5.0.3 on 2024-09-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoursinrestaurant", "0004_remarks"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coworking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("begin", models.DateField(verbose_name="Gültig von")),
                ("end", models.DateField(verbose_name="Gültig bis")),
                ("hours", models.FloatField(verbose_name="Personenstunden pro Tag")),
            ],
            options={
                "verbose_name": "Mitarbeit durch Inhaber und Angehörige",
                "verbose_name_plural": "Mitarbeit durch Inhaber und Angehörige",
            },
        ),
    ]
